### ISSUE TITLE
Dangling process instances

### ISSUE THREAD

**Issue by LinqLover** [LinqLover/TelegramSmalltalkBot#19]
Someone (probably @isCzech?) has managed to create a large number of process instances that have not been cleaned up yet:

![image](https://user-images.githubusercontent.com/38782922/111551825-5fa34a80-8781-11eb-8dda-77fafdb4a583.png)

Make sure that such instances indeed have no further strong references in the image outside of the sandbox of the relevant users.

**Comment by isCzech** [comment]
Hi @LinqLover , I hope nothing's broken :o I tested the behavior of the infamous example we are discussing :) The image always answered the active (UI) process was `a Process(85016) in [] in Delay>>wait`. It looks like behind the scenes other processes have been created and not cleaned up (beyond my control unfortunately). Thanks!

**Comment by LinqLover** [comment]
Ouh, that looks _very_ strange:

![image](https://user-images.githubusercontent.com/38782922/111679061-35a16500-8821-11eb-8bca-786a8dfc91e2.png)

> I hope nothing's broken :o

Nothing wrong! This is exactly the kind of pen-testing I have been waiting for! ❤️ 

I'll keep investigating ...

**Comment by LinqLover** [comment]
So, apparently, there have been two overlapping effects:

First, the main bot cycle uses a polling query, i.e. there is a scheduled delay every time until the next update is provided by the Bot API. See [`TelegramBot >> #doOneCycle`](https://github.com/LinqLover/TelegramBot/blob/master/src/TelegramBot-Core.package/TelegramBot.class/instance/doOneCycle.st) and senders of `Semaphore >> #waitTimeoutMSecs:` in `Socket`. I assume that every delay creates a process somewhere under the hood. But this should not be a problem in general because these processes are terminated correctly:

![image](https://user-images.githubusercontent.com/38782922/111779459-739c9880-88b6-11eb-9015-2b96c2192521.png)

Usually, terminated process instances are ready to be deleted by the GC unless referenced anywhere else. Which leads me to the second effect: Because of #20, regular image updates have been malfunctioning for a few hours yesterday. There were plenty of open merge resolution requests in the image, each spawning its own UI process. Also, image backups were broken due to the same reason which means that the GC was probably just not triggered (afaik it is enabled in different intervals, depending on the activity in the image which is very low in a server image like this). Eventually, this means that the dangling process instances have just not been garbage-collected by chance. Now after I have hot-fixed #20, you can see that the total number of process instances also sinks after some time again:

![image](https://user-images.githubusercontent.com/38782922/111782635-8cf31400-88b9-11eb-8633-2170325a04d6.png)

So without further information, I don't assume a general defect here and will close this issue. Thanks for the pen-testing! :-)
